### ISSUE TITLE
"Assistant not found..." message when I try to edit this one assistant.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#172]
Acorn app with commit id - https://github.com/gptscript-ai/desktop/commit/1eeb6f0161e8eee00f8aa1a7ebf2780dee3a8672

I have one assistant which I am not able to edit anymore.
I see the following error on trying to edit this assistant:
<img width="1012" alt="Screenshot 2024-08-15 at 4 44 16 PM" src="https://github.com/user-attachments/assets/1165a7e6-3686-4a31-8744-db29bfce676b">

Following errors are seen in terminal were the app is edited:

```
Error: Unexpected status 400: invalid script request body: json: cannot unmarshal number -1 into Go struct field Script.id of type uint
    at h (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/.next/server/chunks/640.js:21:2070)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async u (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/.next/server/chunks/611.js:6:20448)
    at async /Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:408
    at async rP (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8043)
    at async r5 (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
    at async doRender (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/server/base-server.js:1433:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/server/base-server.js:1594:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/server/base-server.js:1502:28)
    at async NextNodeServer.renderPageComponent (/Users/sangeethahariharan/ui/electron-dist/mac-arm64/Acorn.app/Contents/Resources/app.asar/node_modules/next/dist/server/base-server.js:1919:24) {
  digest: '895912822'
```

This is the content of this assistant which is not different from any other assistant I have with no tools
```
Name: Newtt Assistant sangee
Type: Tool
Context: dynamic-instructions
Chat: true

You are a helpful assistant named New Assistant. When you first start, just introduce yourself and wait for the user's next message.

---
Name: dynamic-instructions
Type: Tool
```

**Note** - I see this problem only with this 1 assistant.

**Comment by sangee2004** [comment]
I continue to see this issue with this 1 assistant when testing with commit id -  `56cadbd577`

**Comment by thedadams** [comment]
If this issue is only seen with that one assistant, then I think it is a problem with just that one assistant.
