### ISSUE TITLE
`[ERROR]  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'digest')` seen in logs

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#257]
Randomly see this error, usually on the editor screen. 

```
 POST /edit?file=https://gateway-api.gptscript.ai/cjellick/mail-test-3rw5j&id=418 200 in 10ms
 POST /edit?file=https://gateway-api.gptscript.ai/cjellick/mail-test-3rw5j&id=418 200 in 141ms
2024-08-22T21:06:30.721Z [server] [ERROR]  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'digest')
    at /Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17710
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-22T21:06:30.723Z [server] [ERROR]  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'digest')
    at /Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17710
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/cjellick/projects/desktop/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 POST /edit?file=https://gateway-api.gptscript.ai/cjellick/mail-test-3rw5j&id=418 200 in 5ms
```

**Comment by sangee2004** [comment]
Tested with build - `f8cb3bd9a7`
Dont see  these errors in logs anymore when creating and editing assistants.
