### ISSUE TITLE
Chat after knowledge is not working

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#400]
Created an agent and added our large knowledge base docs. Refreshed chat and asked a questions. It's not working at all. I see the following logs. Screen shot attached gives the full context of the agent i created

```
2024-09-03T17:53:41.520Z [server] [ERROR]  ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/cjellick/projects/desktop/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:306:20)
    at Socket.<anonymous> (file:///Users/cjellick/projects/desktop/server/app.mjs:372:37)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/cjellick/projects/desktop/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/cjellick/projects/desktop/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2024-09-03T17:53:41.522Z [server] [ERROR]  ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/cjellick/projects/desktop/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:306:20)
    at Socket.<anonymous> (file:///Users/cjellick/projects/desktop/server/app.mjs:372:37)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/cjellick/projects/desktop/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/cjellick/projects/desktop/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2024-09-03T17:54:18.709Z [server] [ERROR]  ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/cjellick/projects/desktop/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:306:20)
    at Socket.<anonymous> (file:///Users/cjellick/projects/desktop/server/app.mjs:372:37)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/cjellick/projects/desktop/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/cjellick/projects/desktop/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2024-09-03T17:54:18.709Z [server] [ERROR]  ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/cjellick/projects/desktop/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:306:20)
    at Socket.<anonymous> (file:///Users/cjellick/projects/desktop/server/app.mjs:372:37)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/cjellick/projects/desktop/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/cjellick/projects/desktop/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```
![Screenshot 2024-09-03 at 10 54 13 AM](https://github.com/user-attachments/assets/fde8f3f6-df04-4eae-b888-20dbb500fe02)

**Comment by tylerslaton** [comment]
I'm seeing this as working now. Kicking it to testing to reconfirm.

**Comment by sangee2004** [comment]
Tested with `18eaca7d`

I am able to chat with knowledge after files are ingested. I do see other issues relating to this workflow which is tracked in

https://github.com/gptscript-ai/desktop/issues/491
https://github.com/gptscript-ai/desktop/issues/492
